ECHO OFF
SET DEBUG_VALUE=ON
SET DIR_SOURCE=source\
SET DIR_BUILD=win_mingw_build

IF NOT EXIST %DIR_BUILD% MKDIR %DIR_BUILD%

cd %DIR_BUILD%
cmake -G "MinGW Makefiles" ..\%DIR_SOURCE% -DRENGINE_DEBUG=%DEBUG_VALUE%
cd ..